version: '3'

services:
  backend:
    image: niteshmore/backend-image:latest
    env_file:
      .env
    ports:
      - "5000:5000"
  frontend:
    image: niteshmore/frontend-image:latest
    ports:
      - "80:80"