services:
  - type: web
    name: backend
    runtime: image
    image:
      url: niteshmore/backend-image:latest

  - type: web
    name: frontend
    runtime: image
    image:
      url: niteshmore/frontend-image:latest