services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
