services:
  - type: web
    name: backend
    runtime: docker
    image:
      url: niteshmore/backend-image:latest
    envVars:
      - key: PORT
        value: 5000
    ports:
      - 5000

  - type: web
    name: frontend
    runtime: docker
    image:
      url: niteshmore/frontend-image:latest
    envVars:
      - key: PORT
        value: 3000
    ports:
      - 3000
